# Copyright (C) 2026 Akselos
"""Brings existing knowledge into the site whatever shape it arrived in.

Phase 1 is not a template to fill in — it is the material you already have: an AI chat export, a
requirements CSV, meeting notes, a spec, a mail thread you pasted into a text file. This converts each
of those into a markdown doc the builder can render, **without changing the original**, and registers
it in `site.json`.

    python intake.py inputs/*                       # convert everything in inputs/
    python intake.py notes.txt --title "Kickoff notes" --date 2026-07-20
    python intake.py chat.md --kind chat             # force chat formatting
    python intake.py requirements.csv --kind table

Handled: `.md` (copied through), `.txt`/`.log` (paragraphs kept; chat transcripts get speaker
formatting), `.csv`/`.tsv` (rendered as a table), `.json` (fenced). Anything else is fenced verbatim,
which is still better than leaving it outside the site.

The generated `00_input_<slug>.md` is an ARTIFACT: it carries a header saying where it came from, and
re-running overwrites it. Edit the original, or promote the content into a hand-written doc.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent

HEADER = """<!-- GENERATED by intake.py from {source} — re-running overwrites this file.
     The original is the source of truth; edit that, not this. -->

# {title}

> **Imported source material.** Converted from `{source}`{dated} by `intake.py`. This is prior
> knowledge, not an audited claim — nothing here has been checked against code yet. Whatever the
> harness later confirms, contradicts or supersedes shows up as dated layers on the claim.

"""

CHAT_LINE = re.compile(r'^\s*(?P<who>(?:[A-Z][\w .\'-]{0,28}|user|assistant|human|me|you))\s*[:>]\s+(?P<what>.*)$',
                       re.IGNORECASE)


def slugify(text: str) -> str:
    return re.sub(r'[^a-z0-9]+', '_', text.lower()).strip('_') or 'input'


def looks_like_chat(lines: list[str]) -> bool:
    """A transcript if a decent share of non-blank lines open with a speaker tag."""
    body = [ln for ln in lines if ln.strip()]
    if len(body) < 4:
        return False
    hits = sum(1 for ln in body if CHAT_LINE.match(ln))
    return hits >= max(3, len(body) // 5)


def render_chat(lines: list[str]) -> str:
    """Speaker turns as bold labels + blockquotes, so a long transcript stays skimmable."""
    out: list[str] = []
    current: str | None = None
    for raw in lines:
        m = CHAT_LINE.match(raw)
        if m:
            who = m.group('who').strip()
            if who != current:
                out.append('')
                out.append(f'**{who}**')
                current = who
            text = m.group('what').strip()
            if text:
                out.append(f'> {text}')
        elif raw.strip():
            out.append(f'> {raw.strip()}')
        else:
            out.append('')
    return '\n'.join(out).strip() + '\n'


def render_text(lines: list[str]) -> str:
    """Plain notes: markdown already treats blank-line-separated blocks as paragraphs."""
    return '\n'.join(lines).strip() + '\n'


def render_table(text: str, delimiter: str) -> str:
    rows = list(csv.reader(io.StringIO(text), delimiter=delimiter))
    rows = [r for r in rows if any(cell.strip() for cell in r)]
    if not rows:
        return '_(empty)_\n'
    width = max(len(r) for r in rows)
    rows = [r + [''] * (width - len(r)) for r in rows]
    head, body = rows[0], rows[1:]
    esc = lambda c: c.replace('|', r'\|').strip()  # noqa: E731
    out = ['| ' + ' | '.join(esc(c) for c in head) + ' |',
           '| ' + ' | '.join('---' for _ in head) + ' |']
    out += ['| ' + ' | '.join(esc(c) for c in r) + ' |' for r in body]
    return '\n'.join(out) + f'\n\n_{len(body)} rows._\n'


def render_json(text: str) -> str:
    try:
        pretty = json.dumps(json.loads(text), indent=2, ensure_ascii=False)
    except ValueError:
        pretty = text
    return '```json\n' + pretty.strip() + '\n```\n'


def convert(path: pathlib.Path, kind: str) -> str:
    text = path.read_text(encoding='utf-8', errors='replace')
    lines = text.split('\n')
    if kind == 'auto':
        suffix = path.suffix.lower()
        if suffix == '.md':
            kind = 'markdown'
        elif suffix in ('.csv',):
            kind = 'table'
        elif suffix in ('.tsv',):
            kind = 'tsv'
        elif suffix == '.json':
            kind = 'json'
        elif suffix in ('.txt', '.log', ''):
            kind = 'chat' if looks_like_chat(lines) else 'text'
        else:
            kind = 'verbatim'

    if kind == 'markdown':
        return text if text.endswith('\n') else text + '\n'
    if kind == 'chat':
        return render_chat(lines)
    if kind == 'text':
        return render_text(lines)
    if kind == 'table':
        return render_table(text, ',')
    if kind == 'tsv':
        return render_table(text, '\t')
    if kind == 'json':
        return render_json(text)
    return '```\n' + text.strip() + '\n```\n'


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('files', nargs='+', help='source files to import')
    ap.add_argument('--kind', default='auto',
                    choices=('auto', 'markdown', 'chat', 'text', 'table', 'tsv', 'json', 'verbatim'))
    ap.add_argument('--title', help='doc title (default: derived from the filename)')
    ap.add_argument('--date', default='', help='when this material was produced, YYYY-MM-DD')
    ap.add_argument('--prefix', default='00_input', help='output filename prefix')
    ap.add_argument('--no-register', action='store_true',
                    help='do not add the result to site.json "docs"')
    args = ap.parse_args()

    site_path = HERE / 'site.json'
    site = json.loads(site_path.read_text(encoding='utf-8')) if site_path.exists() else {}
    docs = site.get('docs', [])
    known = {d[2] for d in docs if len(d) > 2}

    made = 0
    for spec in args.files:
        src = pathlib.Path(spec)
        if not src.exists() or src.is_dir():
            print(f'skip (not a file): {spec}', file=sys.stderr)
            continue
        title = args.title or src.stem.replace('_', ' ').replace('-', ' ').strip().capitalize()
        slug = slugify(src.stem)
        out_name = f'{args.prefix}_{slug}.md'
        dated = f', dated {args.date}' if args.date else ''
        body = convert(src, args.kind)
        (HERE / out_name).write_text(
            HEADER.format(source=src.as_posix(), title=title, dated=dated) + body, encoding='utf-8')
        made += 1
        print(f'{src} -> {out_name}')

        if not args.no_register and out_name not in known:
            page = f'doc_{args.prefix}_{slug}.html'
            docs.insert(0, [page, f'Input · {title}', out_name])
            known.add(out_name)

    if made and not args.no_register:
        site['docs'] = docs
        site_path.write_text(json.dumps(site, indent=2) + '\n', encoding='utf-8')
        print(f'registered {made} doc(s) in site.json')
    print('\nnext: python code_index.py && python build_site.py')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
