/**
 * Browser-side replacement for pixel-agents' server asset pipeline.
 *
 * Upstream decoded the sprite PNGs in Node with pngjs and pushed them to the webview
 * as `characterSpritesLoaded` / `floorTilesLoaded` / ... messages. Kanban has no such
 * server step, so the same PNGs are fetched from web-ui/public/assets/office/ and
 * decoded here with createImageBitmap + a 2D canvas. The slicing arithmetic and the
 * RGBA→hex rule are kept byte-identical to upstream so a layout authored against the
 * original renders the same here.
 *
 * The file list comes from asset-index.json / furniture-catalog.json, which are
 * generated by scripts/build-office-asset-index.mjs (the browser cannot readdir).
 */

import { buildDynamicCatalog } from '../layout/furnitureCatalog.js';
import type { LoadedAssetData } from '../layout/furnitureCatalog.js';
import { setFloorSprites } from '../floorTiles.js';
import { setCarpetSprites } from '../sprites/carpetTiles.js';
import { setPetTemplates } from '../sprites/petSpriteData.js';
import { setCharacterTemplates } from '../sprites/spriteData.js';
import type { OfficeLayout, SpriteData } from '../types.js';
import { setWallSprites } from '../wallTiles.js';
import { rgbaToHex } from './decode-png.js';

// ── Atlas geometry (mirrors pixel-agents core/src/assets/constants.ts) ──────────

const CHARACTER_DIRECTIONS = ['down', 'up', 'right'] as const;
const CHAR_FRAME_W = 16;
const CHAR_FRAME_H = 32;
const CHAR_FRAMES_PER_ROW = 7;

const FLOOR_TILE_SIZE = 16;

/** Walls are a 4x4 grid of 16x32 pieces; the grid index is the neighbor bitmask. */
const WALL_PIECE_WIDTH = 16;
const WALL_PIECE_HEIGHT = 32;
const WALL_GRID_COLS = 4;
const WALL_BITMASK_COUNT = 16;

/** Carpets are a 4x4 grid of 16x16 pieces, indexed by marching-squares case. */
const CARPET_TILE_SIZE = 16;
const CARPET_GRID_COLS = 4;
const CARPET_MARCHING_SQUARES_COUNT = 16;

/** Pet sheets are 96x96: two 16x32 rows of 6 frames, then one 32x32 row of 3. */
const PET_FRAME_W = 16;
const PET_FRAME_H = 32;
const PET_SIDE_FRAME_W = 32;
const PET_FRAMES_PER_SET = 3;

const ASSET_BASE = 'assets/office';

// ── Index files ────────────────────────────────────────────────────────────────

interface PetIndexEntry {
  dir: string;
  name: string;
}

interface OfficeAssetIndex {
  characters: string[];
  floors: string[];
  walls: string[];
  carpets: string[];
  pets: PetIndexEntry[];
  defaultLayout: string | null;
}

/** One flattened furniture variant, as emitted by build-office-asset-index.mjs. */
type FurnitureCatalogFile = Array<LoadedAssetData['catalog'][number] & { furniturePath: string }>;

export interface OfficeAssets {
  /** The default layout shipped with the sprites, or null when none is present. */
  defaultLayout: OfficeLayout | null;
  counts: {
    characters: number;
    floors: number;
    wallSets: number;
    carpets: number;
    pets: number;
    furniture: number;
  };
}

// ── PNG decoding ───────────────────────────────────────────────────────────────

interface DecodedPng {
  width: number;
  height: number;
  data: Uint8ClampedArray;
}

function readSprite(
  png: DecodedPng,
  width: number,
  height: number,
  offsetX = 0,
  offsetY = 0,
): SpriteData {
  const sprite: SpriteData = [];
  for (let y = 0; y < height; y++) {
    const row: string[] = [];
    for (let x = 0; x < width; x++) {
      const idx = ((offsetY + y) * png.width + (offsetX + x)) * 4;
      row.push(
        rgbaToHex(
          png.data[idx] ?? 0,
          png.data[idx + 1] ?? 0,
          png.data[idx + 2] ?? 0,
          png.data[idx + 3] ?? 0,
        ),
      );
    }
    sprite.push(row);
  }
  return sprite;
}

async function decodePng(url: string): Promise<DecodedPng> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch office sprite: ${url} (${res.status.toString()})`);
  }
  const bitmap = await createImageBitmap(await res.blob());
  try {
    const canvas = new OffscreenCanvas(bitmap.width, bitmap.height);
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      throw new Error(`Failed to acquire a 2d context while decoding ${url}`);
    }
    // willReadFrequently is pointless here: each sheet is read exactly once.
    ctx.drawImage(bitmap, 0, 0);
    const imageData = ctx.getImageData(0, 0, bitmap.width, bitmap.height);
    return { width: bitmap.width, height: bitmap.height, data: imageData.data };
  } finally {
    bitmap.close();
  }
}

// ── Per-category slicing ───────────────────────────────────────────────────────

async function decodeCharacters(base: string, files: string[]) {
  return Promise.all(
    files.map(async (file) => {
      const png = await decodePng(`${base}/characters/${file}`);
      const byDir: Record<(typeof CHARACTER_DIRECTIONS)[number], SpriteData[]> = {
        down: [],
        up: [],
        right: [],
      };
      CHARACTER_DIRECTIONS.forEach((dir, dirIdx) => {
        const rowOffsetY = dirIdx * CHAR_FRAME_H;
        for (let frame = 0; frame < CHAR_FRAMES_PER_ROW; frame++) {
          byDir[dir].push(
            readSprite(png, CHAR_FRAME_W, CHAR_FRAME_H, frame * CHAR_FRAME_W, rowOffsetY),
          );
        }
      });
      return byDir;
    }),
  );
}

async function decodeFloors(base: string, files: string[]): Promise<SpriteData[]> {
  return Promise.all(
    files.map(async (file) => {
      const png = await decodePng(`${base}/floors/${file}`);
      return readSprite(png, FLOOR_TILE_SIZE, FLOOR_TILE_SIZE);
    }),
  );
}

async function decodeWalls(base: string, files: string[]): Promise<SpriteData[][]> {
  return Promise.all(
    files.map(async (file) => {
      const png = await decodePng(`${base}/walls/${file}`);
      const set: SpriteData[] = [];
      for (let mask = 0; mask < WALL_BITMASK_COUNT; mask++) {
        const ox = (mask % WALL_GRID_COLS) * WALL_PIECE_WIDTH;
        const oy = Math.floor(mask / WALL_GRID_COLS) * WALL_PIECE_HEIGHT;
        set.push(readSprite(png, WALL_PIECE_WIDTH, WALL_PIECE_HEIGHT, ox, oy));
      }
      return set;
    }),
  );
}

async function decodeCarpets(base: string, files: string[]): Promise<SpriteData[][]> {
  return Promise.all(
    files.map(async (file) => {
      const png = await decodePng(`${base}/carpets/${file}`);
      const set: SpriteData[] = [];
      for (let msCase = 0; msCase < CARPET_MARCHING_SQUARES_COUNT; msCase++) {
        const ox = (msCase % CARPET_GRID_COLS) * CARPET_TILE_SIZE;
        const oy = Math.floor(msCase / CARPET_GRID_COLS) * CARPET_TILE_SIZE;
        set.push(readSprite(png, CARPET_TILE_SIZE, CARPET_TILE_SIZE, ox, oy));
      }
      return set;
    }),
  );
}

async function decodePets(base: string, pets: PetIndexEntry[]) {
  return Promise.all(
    pets.map(async (pet) => {
      const png = await decodePng(`${base}/pets/${pet.dir}/pet.png`);
      const row = (y: number, startFrame: number): SpriteData[] => {
        const frames: SpriteData[] = [];
        for (let f = 0; f < PET_FRAMES_PER_SET; f++) {
          frames.push(readSprite(png, PET_FRAME_W, PET_FRAME_H, (startFrame + f) * PET_FRAME_W, y));
        }
        return frames;
      };
      const sideRow: SpriteData[] = [];
      for (let f = 0; f < PET_FRAMES_PER_SET; f++) {
        sideRow.push(
          readSprite(png, PET_SIDE_FRAME_W, PET_FRAME_H, f * PET_SIDE_FRAME_W, PET_FRAME_H * 2),
        );
      }
      return {
        walkDown: row(0, 0),
        idleDown: row(0, PET_FRAMES_PER_SET),
        walkUp: row(PET_FRAME_H, 0),
        idleUp: row(PET_FRAME_H, PET_FRAMES_PER_SET),
        walkRight: sideRow,
      };
    }),
  );
}

async function decodeFurniture(
  base: string,
  catalog: FurnitureCatalogFile,
): Promise<Record<string, SpriteData>> {
  const sprites: Record<string, SpriteData> = {};
  await Promise.all(
    catalog.map(async (entry) => {
      const png = await decodePng(`${base}/${entry.furniturePath}`);
      sprites[entry.id] = readSprite(png, entry.width, entry.height);
    }),
  );
  return sprites;
}

// ── Public entry point ─────────────────────────────────────────────────────────

let loadPromise: Promise<OfficeAssets> | null = null;

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url} (${res.status.toString()})`);
  }
  return (await res.json()) as T;
}

/**
 * Decode every office sprite and push it into the engine's module-level stores.
 *
 * Idempotent and safe to call from several components: the work happens once and
 * later callers await the same promise. Resolves with the bundled default layout,
 * which the caller must apply only after this has settled — `buildDynamicCatalog`
 * has to run before any layout is deserialized or furniture and seats resolve to
 * nothing.
 */
export function loadOfficeAssets(): Promise<OfficeAssets> {
  loadPromise ??= loadOfficeAssetsOnce();
  return loadPromise;
}

async function loadOfficeAssetsOnce(): Promise<OfficeAssets> {
  const base = `${import.meta.env.BASE_URL.replace(/\/$/, '')}/${ASSET_BASE}`;

  const [index, catalog] = await Promise.all([
    fetchJson<OfficeAssetIndex>(`${base}/asset-index.json`),
    fetchJson<FurnitureCatalogFile>(`${base}/furniture-catalog.json`),
  ]);

  const [characters, floors, wallSets, carpetSets, pets, furnitureSprites] = await Promise.all([
    decodeCharacters(base, index.characters),
    decodeFloors(base, index.floors),
    decodeWalls(base, index.walls),
    decodeCarpets(base, index.carpets),
    decodePets(base, index.pets),
    decodeFurniture(base, catalog),
  ]);

  setCharacterTemplates(characters);
  setPetTemplates(
    pets,
    index.pets.map((p) => p.name),
  );
  setFloorSprites(floors);
  setWallSprites(wallSets);
  setCarpetSprites(carpetSets);
  buildDynamicCatalog({ catalog, sprites: furnitureSprites });

  const defaultLayout = index.defaultLayout
    ? await fetchJson<OfficeLayout>(`${base}/${index.defaultLayout}`)
    : null;

  return {
    defaultLayout,
    counts: {
      characters: characters.length,
      floors: floors.length,
      wallSets: wallSets.length,
      carpets: carpetSets.length,
      pets: pets.length,
      furniture: Object.keys(furnitureSprites).length,
    },
  };
}
