"""jacked memory vault -- cross-repo, git-backed, grep-retrieved memory.

M1 public surface (the ``jacked memory`` CLI group leans on these). Later
milestones (capture, recall, rollup, migrate) add sibling modules and extend
the re-exports here.
"""
from __future__ import annotations

from jacked.memory.vault import (
    DEFAULT_DRIFT_THRESHOLD,
    DEFAULT_TRIAGE_MODEL,
    STATE_PATH_NAME,
    STATE_VERSION,
    VALID_TYPES,
    VAULT_CONFIG_NAME,
    VAULT_CONFIG_VERSION,
    VAULT_DIR_ENV,
    add_note,
    bump_drift,
    commit_all,
    ensure_group,
    group_dir,
    group_for_identity,
    init_vault,
    is_initialized,
    jacked_home,
    load_state,
    load_vault_config,
    mark_groomed,
    normalize_remote,
    note_counts,
    parse_frontmatter,
    register_repo,
    render_note,
    repo_identity,
    resolve_group,
    save_state,
    save_vault_config,
    scan_roots,
    search,
    serialize_frontmatter,
    set_enabled,
    slugify,
    state_path,
    status,
    suggest_groups,
    today,
    validate_note,
    vault_config_path,
    vault_dir,
    vault_write_lock,
)

__all__ = [
    "DEFAULT_DRIFT_THRESHOLD",
    "DEFAULT_TRIAGE_MODEL",
    "STATE_PATH_NAME",
    "STATE_VERSION",
    "VALID_TYPES",
    "VAULT_CONFIG_NAME",
    "VAULT_CONFIG_VERSION",
    "VAULT_DIR_ENV",
    "add_note",
    "bump_drift",
    "commit_all",
    "ensure_group",
    "group_dir",
    "group_for_identity",
    "init_vault",
    "is_initialized",
    "jacked_home",
    "load_state",
    "load_vault_config",
    "mark_groomed",
    "normalize_remote",
    "note_counts",
    "parse_frontmatter",
    "register_repo",
    "render_note",
    "repo_identity",
    "resolve_group",
    "save_state",
    "save_vault_config",
    "scan_roots",
    "search",
    "serialize_frontmatter",
    "set_enabled",
    "slugify",
    "state_path",
    "status",
    "suggest_groups",
    "today",
    "validate_note",
    "vault_config_path",
    "vault_dir",
    "vault_write_lock",
]
