/**
 * User-visible copy for the HTML generation surface.
 * Files/types keep html-anything / vendor names for traceability; people see these labels.
 */
export const HTML_LABELS = {
	section: "HTML",
	generate: "Generate HTML",
	offline: "HTML templates offline",
	offlineHint: "Templates appear when the companion sidecar is running.",
	pickTemplate: "Choose a template",
	templates: "Templates",
	collapseTemplates: "Collapse templates",
	expandTemplates: "Show templates",
	templatesLoading: "Loading templates…",
	noPreview: "No preview",
	saveSibling: "Save as HTML plan",
	generateEmpty: "Generation finished without producing any HTML — nothing was saved.",
	preview: "Preview",
	plain: "Source",
	streaming: "Generating…",
	emptyTemplates: "No templates available.",
	convert: "Convert to HTML",
	source: "Source",
	log: "Log",
	elapsed: "Elapsed",
	ttfb: "TTFB",
	size: "Size",
	agent: "Agent",
	online: "Online",
	offlineShort: "Offline",
	noLog: "No log output yet.",
	expand: "Expand brief",
	expandHint:
		"Reorganizes your notes, describes every image in words, and adds a structured brief. The old version is kept as a .bak file.",
	expanding: "Expanding…",
	expandDone: "Brief added below your notes.",
	expandRewrote: "Plan reorganized and brief added. The previous version was saved beside it.",
	expandBackupFailed: "Could not back up the plan, so it was left untouched.",
	expandNeedsPlan: "Save the plan first — expansion reads its images from disk.",
	expandEmpty: "The expander finished without writing anything — nothing was added to your notes.",
	refine: "Refine",
	refineHint: "Applies just your edits to the HTML you already have, instead of regenerating it.",
	refineNeedsHtml: "Generate HTML once before refining it.",
	refineUnchanged: "Nothing to refine — the notes have not changed since this HTML was generated.",
	refineNoBase: "No record of what this HTML was generated from, so refining sends the whole document.",
	refineWholeRewrite: "The notes changed too much for a partial edit, so refining sends the whole document.",
	aiPlaceholder: 'Ask AI to write markdown — "draft a section about X", "add a risks table"…',
	aiPlaceholderSelection: 'Rewrite the selected text — "make it shorter", "turn this into a table"…',
	aiSubmit: "Draft",
	aiSubmitSelection: "Rewrite",
	aiStop: "Stop",
	aiAttach: "Attach",
	aiHint: "Send the instruction (⌘↵)",
	aiSelectionHint: "Select text in the source pane to rewrite it in place instead.",
	aiDraftDone: "Draft added below your notes.",
	aiEditDone: "Selected text rewritten.",
	aiEmpty: "The agent finished without writing anything — your notes were left unchanged.",
} as const;
