/**
 * User-visible copy for the HTML generation surface.
 * Files/types keep html-anything / vendor names for traceability; people see these labels.
 */
export const HTML_LABELS = {
	section: "HTML",
	generate: "Generate HTML",
	offline: "HTML templates offline",
	offlineHint: "Templates appear when the companion sidecar is running.",
	pickTemplate: "Choose a template",
	noTemplate: "No template",
	noTemplateHint: "No template selected — the page is built straight from your markdown, images included.",
	deselectTemplate: "Selected. Click again to build from your markdown alone.",
	templates: "Templates",
	collapseTemplates: "Collapse templates",
	expandTemplates: "Show templates",
	templatesLoading: "Loading templates…",
	noPreview: "No preview",
	importTemplate: "Import template",
	importTemplateHint: "Install a template from a .zip holding SKILL.md, example.md and example.html.",
	importingTemplate: "Installing template…",
	importTemplateDone: "Template installed.",
	importTemplateReplaced: "Template replaced.",
	saveSibling: "Save as HTML plan",
	generateEmpty: "Generation finished without producing any HTML — nothing was saved.",
	preview: "Preview",
	plain: "Source",
	streaming: "Generating…",
	emptyTemplates: "No templates available.",
	convert: "Convert to HTML",
	source: "Source",
	log: "Log",
	elapsed: "Elapsed",
	ttfb: "TTFB",
	size: "Size",
	agent: "Agent",
	online: "Online",
	offlineShort: "Offline",
	noLog: "No log output yet.",
	expand: "Expand brief",
	expandHint:
		"Reorganizes your notes, describes every image in words, and adds a structured brief. The old version is kept as a .bak file.",
	expanding: "Expanding…",
	expandDone: "Brief added below your notes.",
	expandRewrote: "Plan reorganized and brief added. The previous version was saved beside it.",
	expandBackupFailed: "Could not back up the plan, so it was left untouched.",
	expandNeedsPlan: "Save the plan first — expansion reads its images from disk.",
	expandEmpty: "The expander finished without writing anything — nothing was added to your notes.",
	refine: "Refine",
	refineHint: "Applies just your edits to the HTML you already have, instead of regenerating it.",
	refineNeedsHtml: "Generate HTML once before refining it.",
	refineUnchanged: "Nothing to refine — the notes have not changed since this HTML was generated.",
	refineNoBase: "No record of what this HTML was generated from, so refining sends the whole document.",
	refineWholeRewrite: "The notes changed too much for a partial edit, so refining sends the whole document.",
	aiPlaceholder: 'Ask AI to write markdown — "draft a section about X", "add a risks table"…',
	aiPlaceholderSelection: 'Rewrite the selected text — "make it shorter", "turn this into a table"…',
	aiSubmit: "Draft",
	aiSubmitSelection: "Rewrite",
	aiStop: "Stop",
	aiAttach: "Attach",
	aiHint: "Send the instruction (⌘↵)",
	aiSelectionHint: "Select text in the source pane to rewrite it in place instead.",
	aiDraftDone: "Draft added below your notes.",
	aiEditDone: "Selected text rewritten.",
	aiEmpty: "The agent finished without writing anything — your notes were left unchanged.",
	history: "History",
	historyHint: "Every recorded version of this plan's notes and generated page.",
	historyEmpty: "No versions recorded yet.",
	historyCurrent: "on disk",
	historyDiff: "Diff",
	historyDiffHint: "Compare this version with the file as it stands now.",
	historyDiffUnavailable: "That version can no longer be compared.",
	historyNoChanges: "Identical to the current file.",
	historyRestore: "Restore this version",
	historyRestored: "Version restored.",
	undo: "Undo",
	undoHint: "Step back to the previous recorded version of this document.",
	redo: "Redo",
	redoHint: "Step forward to the next recorded version of this document.",
	historyNothingOlder: "Nothing older was recorded for this document.",
	historyNothingNewer: "Already at the newest recorded version.",
	deploy: "Deploy",
	deploying: "Deploying…",
	deployTitle: "Deploy to Google Workspace",
	deployHint: "Publish this page as an Apps Script web app, visible to your Workspace only.",
	deployNeedsHtml: "Generate HTML before deploying it.",
	deployRun: "Deploy now",
	deployRedeploy: "Deploy update",
	deployDone: "Deployed. The link is in the deploy dialog.",
	deployFailed: "Deploy failed — see the log in the deploy dialog.",
	deploySignIn: "Sign in with Google",
	deploySignInAgain: "Sign in as someone else",
	deploySignInHint: "Opens the Google consent screen in the browser profile configured below.",
	deploySignedInAs: "Signed in as",
	deploySignedOut: "Not signed in to Google yet.",
	deployConsentOpen: "Waiting for the Google consent screen…",
	deployConsentManual: "Not signing in? Open this URL yourself:",
	deployPasteCode: "Paste the code from Google",
	deployPasteCodeSubmit: "Finish sign-in",
	deployUseCodeFlow: "Browser can't reach this app? Use the paste-a-code sign-in.",
	deployProfileSection: "Browser profile",
	deployProfileHint:
		"Chrome's profile folder name — Default, Profile 1, … — for the profile already signed in as your Workspace account.",
	deployProfilePathHint: "Path to the browser binary. On WSL this is the Windows chrome.exe.",
	deployProfileSave: "Save",
	deployProfileSaved: "Browser profile saved.",
	deployProfileMissing: "No browser profile configured — sign-in will use your default browser.",
	deployAccess: "Access",
	deployAccessValue: "Anyone in",
	deployNeedsApi: "Turn on the Apps Script API for this Google account, then deploy again.",
	deployNeedsApiAction: "Open Apps Script settings",
	deployNeedsNetwork: "Could not reach Google. Check the network and try again.",
	deployCurrent: "Current deployment",
	deployOpen: "Open",
	deployCopy: "Copy link",
	deployCopied: "Link copied.",
	deployLog: "Deploy log",
	viewEditorOnly: "Editor only",
	viewSplit: "Split view",
	viewPreviewOnly: "Preview only",
} as const;
