import { readFile, rm, writeFile } from "node:fs/promises";
import { extname, join, resolve } from "node:path";

import { isPathWithinRoot } from "../workspace/path-sandbox";

/** Apps Script serves a single HTML file; anything the page needs has to be inside it. */
export const MAX_PAGE_BYTES = 10 * 1024 * 1024;

export const APPS_SCRIPT_PAGE_FILE = "Page.html";
export const APPS_SCRIPT_CODE_FILE = "Code.gs";
export const APPS_SCRIPT_MANIFEST_FILE = "appsscript.json";
export const CLASP_PROJECT_FILE = ".clasp.json";

const MIME_TYPE_BY_EXTENSION: Record<string, string> = {
	".png": "image/png",
	".jpg": "image/jpeg",
	".jpeg": "image/jpeg",
	".gif": "image/gif",
	".webp": "image/webp",
	".svg": "image/svg+xml",
	".ico": "image/x-icon",
	".css": "text/css",
	".js": "text/javascript",
	".json": "application/json",
	".woff": "font/woff",
	".woff2": "font/woff2",
	".ttf": "font/ttf",
	".otf": "font/otf",
};

/** `src="…"` / `href="…"` and CSS `url(…)` — everything a generated page uses to reach a file. */
const REFERENCE_PATTERNS: RegExp[] = [
	/(\s(?:src|href)\s*=\s*")([^"]+)(")/gi,
	/(\s(?:src|href)\s*=\s*')([^']+)(')/gi,
	/(url\(\s*")([^"]+)("\s*\))/gi,
	/(url\(\s*')([^']+)('\s*\))/gi,
	/(url\(\s*)([^"')\s]+)(\s*\))/gi,
];

function isExternalReference(link: string): boolean {
	const trimmed = link.trim();
	if (trimmed.length === 0) {
		return true;
	}
	// Scheme-qualified (`https:`, `data:`, `mailto:`), protocol-relative, or in-page anchors:
	// nothing local to read, so nothing to inline.
	return /^[a-z][a-z0-9+.-]*:/i.test(trimmed) || trimmed.startsWith("//") || trimmed.startsWith("#");
}

export interface InlineAssetsResult {
	html: string;
	/** Relative links that became data URIs. */
	inlined: string[];
	/** Relative links that could not be read, left pointing at a path Apps Script cannot serve. */
	skipped: string[];
}

/**
 * Rewrite every local file the page references into a `data:` URI.
 *
 * Apps Script's HtmlService serves exactly the files in the script project, and a script
 * project is flat — there is no `<stem>.assets/` to upload alongside the page. Locally
 * those links resolve through the runtime's `/api/plans/asset` route, so a page that looks
 * perfect in the preview would deploy with every image broken. Sandboxed to the plan's own
 * folder, matching `readSavedPlanAsset`.
 */
export async function inlinePlanHtmlAssets(html: string, planDir: string): Promise<InlineAssetsResult> {
	const inlined = new Set<string>();
	const skipped = new Set<string>();
	const cache = new Map<string, string | null>();

	const readAsDataUri = async (link: string): Promise<string | null> => {
		const cached = cache.get(link);
		if (cached !== undefined) {
			return cached;
		}
		let dataUri: string | null = null;
		try {
			// Query/fragment suffixes are cache-busters on a local path, not part of the file name.
			const cleanLink = decodeURI(link.split("?")[0]?.split("#")[0] ?? link);
			const resolvedPath = resolve(planDir, cleanLink);
			if (isPathWithinRoot(planDir, resolvedPath)) {
				const content = await readFile(resolvedPath);
				const mimeType = MIME_TYPE_BY_EXTENSION[extname(resolvedPath).toLowerCase()] ?? "application/octet-stream";
				dataUri = `data:${mimeType};base64,${content.toString("base64")}`;
			}
		} catch {
			dataUri = null;
		}
		cache.set(link, dataUri);
		return dataUri;
	};

	let result = html;
	for (const pattern of REFERENCE_PATTERNS) {
		const matches = [...result.matchAll(pattern)];
		const replacements = await Promise.all(
			matches.map(async (match) => {
				const link = match[2] ?? "";
				if (isExternalReference(link)) {
					return null;
				}
				const dataUri = await readAsDataUri(link);
				if (dataUri === null) {
					skipped.add(link);
					return null;
				}
				inlined.add(link);
				return { from: match[0], to: `${match[1] ?? ""}${dataUri}${match[3] ?? ""}` };
			}),
		);
		for (const replacement of replacements) {
			if (replacement) {
				result = result.split(replacement.from).join(replacement.to);
			}
		}
	}

	return { html: result, inlined: [...inlined], skipped: [...skipped] };
}

export function buildAppsScriptManifest(input: { timeZone: string }): string {
	return `${JSON.stringify(
		{
			timeZone: input.timeZone,
			dependencies: {},
			exceptionLogging: "STACKDRIVER",
			runtimeVersion: "V8",
			webapp: {
				// USER_DEPLOYING + DOMAIN is what keeps the page inside the Workspace: it runs as
				// the deploying account and is reachable only by signed-in members of its domain.
				executeAs: "USER_DEPLOYING",
				access: "DOMAIN",
			},
		},
		null,
		2,
	)}\n`;
}

export function buildAppsScriptCode(title: string): string {
	const safeTitle = JSON.stringify(title);
	return `/** Generated by the Plan Editor — edits here are overwritten on the next deploy. */
function doGet() {
  return HtmlService.createHtmlOutputFromFile('Page')
    .setTitle(${safeTitle})
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}
`;
}

export interface WriteBundleInput {
	dir: string;
	html: string;
	planDir: string;
	title: string;
	timeZone: string;
	/** Set for a re-deploy so the push targets the existing script instead of creating one. */
	scriptId?: string | null;
}

export interface WriteBundleResult {
	pageBytes: number;
	inlined: string[];
	skipped: string[];
}

export async function writeAppsScriptBundle(input: WriteBundleInput): Promise<WriteBundleResult> {
	const { html, inlined, skipped } = await inlinePlanHtmlAssets(input.html, input.planDir);
	const pageBytes = Buffer.byteLength(html, "utf8");
	if (pageBytes > MAX_PAGE_BYTES) {
		throw new Error(
			`The page is ${(pageBytes / 1024 / 1024).toFixed(1)} MB once its images are inlined, over the ${
				MAX_PAGE_BYTES / 1024 / 1024
			} MB deploy limit. Shrink or link the largest images and generate again.`,
		);
	}

	await writeFile(join(input.dir, APPS_SCRIPT_PAGE_FILE), html, "utf8");
	await writeFile(join(input.dir, APPS_SCRIPT_CODE_FILE), buildAppsScriptCode(input.title), "utf8");
	await writeFile(
		join(input.dir, APPS_SCRIPT_MANIFEST_FILE),
		buildAppsScriptManifest({ timeZone: input.timeZone }),
		"utf8",
	);
	if (input.scriptId) {
		await writeFile(
			join(input.dir, CLASP_PROJECT_FILE),
			`${JSON.stringify({ scriptId: input.scriptId }, null, 2)}\n`,
			"utf8",
		);
	}
	// `clasp create` seeds a `Code.js` whose own function would collide with ours.
	await rm(join(input.dir, "Code.js"), { force: true });

	return { pageBytes, inlined, skipped };
}
